version: '3.9'
services:
  postgres:
    image: postgres:16-alpine
    container_name: smartscholar-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: smartscholar
    ports:
      - "5432:5432"
    volumes:
      - smartscholar_pg_data:/var/lib/postgresql/data

volumes:
  smartscholar_pg_data:
